/*
 Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function g(a,b){var c=[];if(b)for(var e in b)c.push(e+"\x3d"+encodeURIComponent(b[e]));else return a;return a+(-1!=a.indexOf("?")?"\x26":"?")+c.join("\x26")}function r(a){return!a.match(/command=QuickUpload/)||a.match(/(\?|&)responseType=json/)?a:g(a,{responseType:"json"})}function h(a){a+="";return a.charAt(0).toUpperCase()+a.substr(1)}function t(){var a=this.getDialog(),b=a.getParentEditor();b._.filebrowserSe=this;var c=this.filebrowser.params||{};c.CKEditor=b.name;c.CKEditorFuncNum=
b._.filebrowserFn;c.langCode||(c.langCode=b.langCode);if(u(this.filebrowser.url))this.filebrowser.url(a,c,function(a,c){l(a,c,b._.filebrowserSe)});else{var e=b.config["filebrowser"+h(a.getName())+"WindowWidth"]||b.config.filebrowserWindowWidth||"80%",a=b.config["filebrowser"+h(a.getName())+"WindowHeight"]||b.config.filebrowserWindowHeight||"70%",c=g(this.filebrowser.url,c);b.popup(c,e,a,b.config.filebrowserWindowFeatures||b.config.fileBrowserWindowFeatures,b.config.filebrowserWindowName)}}function u(a){return a&&
"[object Function]"==={}.toString.call(a)}function v(a){var b=new CKEDITOR.dom.element(a.$.form);b&&((a=b.$.elements.ckCsrfToken)?a=new CKEDITOR.dom.element(a):(a=new CKEDITOR.dom.element("input"),a.setAttributes({name:"ckCsrfToken",type:"hidden"}),b.append(a)),a.setAttribute("value",CKEDITOR.tools.getCsrfToken()))}function w(){var a=this.getDialog();a.getParentEditor()._.filebrowserSe=this;return a.getContentElement(this["for"][0],this["for"][1]).getInputElement().$.value&&a.getContentElement(this["for"][0],
this["for"][1]).getAction()?!0:!1}function x(a,b,c){var e=c.params||{};e.CKEditor=a.name;e.CKEditorFuncNum=a._.filebrowserFn;e.langCode||(e.langCode=a.langCode);b.action=g(c.url,e);b.filebrowser=c}function m(a,b,c,e){if(e&&e.length)for(var d,k=e.length;k--;)if(d=e[k],"hbox"!=d.type&&"vbox"!=d.type&&"fieldset"!=d.type||m(a,b,c,d.children),d.filebrowser)if("string"==typeof d.filebrowser&&(d.filebrowser={action:"fileButton"==d.type?"QuickUpload":"Browse",target:d.filebrowser}),"Browse"==d.filebrowser.action){var f=
d.filebrowser.url;void 0===f&&(f=a.config["filebrowser"+h(b)+"BrowseUrl"],void 0===f&&(f=a.config.filebrowserBrowseUrl));f&&(d.onClick=t,d.filebrowser.url=f,d.hidden=!1)}else if("QuickUpload"==d.filebrowser.action&&d["for"]&&(f=d.filebrowser.url,void 0===f&&(f=a.config["filebrowser"+h(b)+"UploadUrl"],void 0===f&&(f=a.config.filebrowserUploadUrl)),f)){var g=d.onClick;d.onClick=function(b){var c=b.sender,d=c.getDialog().getContentElement(this["for"][0],this["for"][1]).getInputElement(),e=CKEDITOR.fileTools&&
CKEDITOR.fileTools.isFileUploadSupported;if(g&&!1===g.call(c,b))return!1;if(w.call(c,b)){if("form"!==a.config.filebrowserUploadMethod&&e)return b=a.uploadRepository.create(d.$.files[0]),b.on("uploaded",function(a){var b=a.sender.responseData;n.call(a.sender.editor,b.url,b.message)}),b.on("error",p.bind(this)),b.on("abort",p.bind(this)),b.loadAndUpload(r(f)),"xhr";v(d);return!0}return!1};d.filebrowser.url=f;d.hidden=!1;x(a,c.getContents(d["for"][0]).get(d["for"][1]),d.filebrowser)}}function p(a){var b=
{};try{b=JSON.parse(a.sender.xhr.response)||{}}catch(c){}this.enable();alert(b.error?b.error.message:a.sender.message)}function q(a,b,c){if(-1!==c.indexOf(";")){c=c.split(";");for(var e=0;e<c.length;e++)if(q(a,b,c[e]))return!0;return!1}return(a=a.getContents(b).get(c).filebrowser)&&a.url}function n(a,b){l(a,b,this._.filebrowserSe)}function l(a,b,c){var e=c.getDialog(),d=c["for"],g=c.filebrowser.onSelect;d&&e.getContentElement(d[0],d[1]).reset();if("function"!=typeof b||!1!==b.call(c))if(!g||!1!==
g.call(c,a,b))if("string"==typeof b&&b&&alert(b),a&&(b=c.getDialog(),c=c.filebrowser.target||null))if(c=c.split(":"),e=b.getContentElement(c[0],c[1]))e.setValue(a),b.selectPage(c[0])}CKEDITOR.plugins.add("filebrowser",{requires:"popup,filetools",init:function(a){a._.filebrowserFn=CKEDITOR.tools.addFunction(n,a);a.on("destroy",function(){CKEDITOR.tools.removeFunction(this._.filebrowserFn)})}});CKEDITOR.on("dialogDefinition",function(a){if(a.editor.plugins.filebrowser)for(var b=a.data.definition,c,
e=0;e<b.contents.length;++e)if(c=b.contents[e])m(a.editor,a.data.name,b,c.elements),c.hidden&&c.filebrowser&&(c.hidden=!q(b,c.id,c.filebrowser))})})();